// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotorTechService.Data;

#nullable disable

namespace MotorTechService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251119222913_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.CategoriaRepuesto", b =>
                {
                    b.Property<int>("CategoriaRepuestoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaRepuestoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoriaRepuestoId");

                    b.ToTable("CategoriasRepuesto");

                    b.HasData(
                        new
                        {
                            CategoriaRepuestoId = 1,
                            Activo = true,
                            Descripcion = "Filtros de aire, aceite, combustible",
                            Nombre = "Filtros"
                        },
                        new
                        {
                            CategoriaRepuestoId = 2,
                            Activo = true,
                            Descripcion = "Aceites y lubricantes",
                            Nombre = "Lubricantes"
                        },
                        new
                        {
                            CategoriaRepuestoId = 3,
                            Activo = true,
                            Descripcion = "Pastillas, discos, líquido frenos",
                            Nombre = "Frenos"
                        },
                        new
                        {
                            CategoriaRepuestoId = 4,
                            Activo = true,
                            Descripcion = "Repuestos del motor",
                            Nombre = "Motor"
                        },
                        new
                        {
                            CategoriaRepuestoId = 5,
                            Activo = true,
                            Descripcion = "Componentes eléctricos",
                            Nombre = "Eléctrico"
                        });
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.CategoriaServicio", b =>
                {
                    b.Property<int>("CategoriaServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaServicioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoriaServicioId");

                    b.ToTable("CategoriasServicio");

                    b.HasData(
                        new
                        {
                            CategoriaServicioId = 1,
                            Activo = true,
                            Descripcion = "Servicios de mantenimiento regular",
                            Nombre = "Mantenimiento Preventivo"
                        },
                        new
                        {
                            CategoriaServicioId = 2,
                            Activo = true,
                            Descripcion = "Reparaciones del sistema motor",
                            Nombre = "Reparaciones Motor"
                        },
                        new
                        {
                            CategoriaServicioId = 3,
                            Activo = true,
                            Descripcion = "Reparaciones sistema eléctrico",
                            Nombre = "Sistema Eléctrico"
                        },
                        new
                        {
                            CategoriaServicioId = 4,
                            Activo = true,
                            Descripcion = "Mantenimiento y reparación frenos",
                            Nombre = "Frenos"
                        },
                        new
                        {
                            CategoriaServicioId = 5,
                            Activo = true,
                            Descripcion = "Reparaciones transmisión",
                            Nombre = "Transmisión"
                        });
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DocumentoIdentidad")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ClienteId");

                    b.HasIndex("DocumentoIdentidad")
                        .IsUnique()
                        .HasFilter("[DocumentoIdentidad] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.Configuracion", b =>
                {
                    b.Property<int>("ConfiguracionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfiguracionId"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ConfiguracionId");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("Configuraciones");

                    b.HasData(
                        new
                        {
                            ConfiguracionId = 1,
                            Clave = "NombreTaller",
                            Descripcion = "Nombre del taller",
                            FechaModificacion = new DateTime(2025, 11, 19, 14, 29, 12, 110, DateTimeKind.Local).AddTicks(5621),
                            Tipo = "string",
                            Valor = "Taller Mecánico P&F"
                        },
                        new
                        {
                            ConfiguracionId = 2,
                            Clave = "TelefonoTaller",
                            Descripcion = "Teléfono del taller",
                            FechaModificacion = new DateTime(2025, 11, 19, 14, 29, 12, 110, DateTimeKind.Local).AddTicks(5626),
                            Tipo = "string",
                            Valor = "555-0123"
                        },
                        new
                        {
                            ConfiguracionId = 3,
                            Clave = "EmailTaller",
                            Descripcion = "Email del taller",
                            FechaModificacion = new DateTime(2025, 11, 19, 14, 29, 12, 110, DateTimeKind.Local).AddTicks(5628),
                            Tipo = "string",
                            Valor = "info@tallerpyf.com"
                        },
                        new
                        {
                            ConfiguracionId = 4,
                            Clave = "DireccionTaller",
                            Descripcion = "Dirección del taller",
                            FechaModificacion = new DateTime(2025, 11, 19, 14, 29, 12, 110, DateTimeKind.Local).AddTicks(5630),
                            Tipo = "string",
                            Valor = "Calle Principal 123"
                        },
                        new
                        {
                            ConfiguracionId = 5,
                            Clave = "PorcentajeImpuesto",
                            Descripcion = "Porcentaje de impuesto",
                            FechaModificacion = new DateTime(2025, 11, 19, 14, 29, 12, 110, DateTimeKind.Local).AddTicks(5631),
                            Tipo = "decimal",
                            Valor = "12.0"
                        },
                        new
                        {
                            ConfiguracionId = 6,
                            Clave = "MonedaPrincipal",
                            Descripcion = "Moneda principal",
                            FechaModificacion = new DateTime(2025, 11, 19, 14, 29, 12, 110, DateTimeKind.Local).AddTicks(5633),
                            Tipo = "string",
                            Valor = "USD"
                        });
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaTerminacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PorcentajeComision")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("SalarioHora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("DocumentoIdentidad")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.Factura", b =>
                {
                    b.Property<int>("FacturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacturaId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Impuestos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OrdenTrabajoId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FacturaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("NumeroFactura")
                        .IsUnique();

                    b.HasIndex("OrdenTrabajoId");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.HistorialMantenimiento", b =>
                {
                    b.Property<int>("HistorialMantenimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistorialMantenimientoId"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaServicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("KilometrajeServicio")
                        .HasColumnType("int");

                    b.Property<int?>("OrdenTrabajoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoServicio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("HistorialMantenimientoId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("OrdenTrabajoId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("HistorialMantenimientos");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.HistorialOrden", b =>
                {
                    b.Property<int>("HistorialOrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistorialOrdenId"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoAnterior")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrdenTrabajoId")
                        .HasColumnType("int");

                    b.HasKey("HistorialOrdenId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("OrdenTrabajoId");

                    b.ToTable("HistorialOrdenes");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.MovimientoInventario", b =>
                {
                    b.Property<int>("MovimientoInventarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovimientoInventarioId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal?>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DocumentoReferencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RepuestoId")
                        .HasColumnType("int");

                    b.Property<int>("StockAnterior")
                        .HasColumnType("int");

                    b.Property<int>("StockNuevo")
                        .HasColumnType("int");

                    b.Property<int>("TipoMovimiento")
                        .HasColumnType("int");

                    b.HasKey("MovimientoInventarioId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("RepuestoId");

                    b.ToTable("MovimientosInventario");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.OrdenTrabajo", b =>
                {
                    b.Property<int>("OrdenTrabajoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdenTrabajoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("AutorizadoPorCliente")
                        .HasColumnType("bit");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionProblema")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DiagnosticoTecnico")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("EmpleadoAsignadoId")
                        .HasColumnType("int");

                    b.Property<int?>("EmpleadoRecepcionId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPromesaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Impuestos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroOrden")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ObservacionesCliente")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("RecomendacionesTecnico")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("RequiereAutorizacion")
                        .HasColumnType("bit");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("OrdenTrabajoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpleadoAsignadoId");

                    b.HasIndex("EmpleadoRecepcionId");

                    b.HasIndex("NumeroOrden")
                        .IsUnique();

                    b.HasIndex("VehiculoId");

                    b.ToTable("OrdenesTrabajo");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.OrdenTrabajoRepuesto", b =>
                {
                    b.Property<int>("OrdenTrabajoRepuestoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdenTrabajoRepuestoId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("Entregado")
                        .HasColumnType("bit");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrdenTrabajoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RepuestoId")
                        .HasColumnType("int");

                    b.HasKey("OrdenTrabajoRepuestoId");

                    b.HasIndex("OrdenTrabajoId");

                    b.HasIndex("RepuestoId");

                    b.ToTable("OrdenTrabajoRepuestos");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.OrdenTrabajoServicio", b =>
                {
                    b.Property<int>("OrdenTrabajoServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdenTrabajoServicioId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<bool>("Completado")
                        .HasColumnType("bit");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrdenTrabajoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.HasKey("OrdenTrabajoServicioId");

                    b.HasIndex("OrdenTrabajoId");

                    b.HasIndex("ServicioId");

                    b.ToTable("OrdenTrabajoServicios");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroReferencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TipoPago")
                        .HasColumnType("int");

                    b.HasKey("PagoId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("FacturaId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.RegistroTiempo", b =>
                {
                    b.Property<int>("RegistroTiempoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistroTiempoId"));

                    b.Property<decimal?>("CostoHora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("MinutosTrabajados")
                        .HasColumnType("int");

                    b.Property<int?>("OrdenTrabajoId")
                        .HasColumnType("int");

                    b.HasKey("RegistroTiempoId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("OrdenTrabajoId");

                    b.ToTable("RegistrosTiempo");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.Repuesto", b =>
                {
                    b.Property<int>("RepuestoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepuestoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaRepuestoId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PorcentajeGanancia")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StockActual")
                        .HasColumnType("int");

                    b.Property<int>("StockMaximo")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RepuestoId");

                    b.HasIndex("CategoriaRepuestoId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Repuestos");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.Servicio", b =>
                {
                    b.Property<int>("ServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServicioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaServicioId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("RequiereAutorizacion")
                        .HasColumnType("bit");

                    b.Property<int>("TiempoEstimadoMinutos")
                        .HasColumnType("int");

                    b.HasKey("ServicioId");

                    b.HasIndex("CategoriaServicioId");

                    b.ToTable("Servicios");

                    b.HasData(
                        new
                        {
                            ServicioId = 1,
                            Activo = true,
                            CategoriaServicioId = 1,
                            Descripcion = "Cambio de aceite motor",
                            FechaCreacion = new DateTime(2025, 11, 19, 14, 29, 12, 110, DateTimeKind.Local).AddTicks(5508),
                            Nombre = "Cambio de Aceite",
                            PrecioBase = 25.00m,
                            RequiereAutorizacion = false,
                            TiempoEstimadoMinutos = 30
                        },
                        new
                        {
                            ServicioId = 2,
                            Activo = true,
                            CategoriaServicioId = 1,
                            Descripcion = "Alineación de ruedas",
                            FechaCreacion = new DateTime(2025, 11, 19, 14, 29, 12, 110, DateTimeKind.Local).AddTicks(5559),
                            Nombre = "Alineación",
                            PrecioBase = 40.00m,
                            RequiereAutorizacion = false,
                            TiempoEstimadoMinutos = 60
                        },
                        new
                        {
                            ServicioId = 3,
                            Activo = true,
                            CategoriaServicioId = 1,
                            Descripcion = "Balanceo de ruedas",
                            FechaCreacion = new DateTime(2025, 11, 19, 14, 29, 12, 110, DateTimeKind.Local).AddTicks(5562),
                            Nombre = "Balanceo",
                            PrecioBase = 30.00m,
                            RequiereAutorizacion = false,
                            TiempoEstimadoMinutos = 45
                        },
                        new
                        {
                            ServicioId = 4,
                            Activo = true,
                            CategoriaServicioId = 2,
                            Descripcion = "Diagnóstico completo motor",
                            FechaCreacion = new DateTime(2025, 11, 19, 14, 29, 12, 110, DateTimeKind.Local).AddTicks(5564),
                            Nombre = "Revisión Motor",
                            PrecioBase = 80.00m,
                            RequiereAutorizacion = true,
                            TiempoEstimadoMinutos = 120
                        },
                        new
                        {
                            ServicioId = 5,
                            Activo = true,
                            CategoriaServicioId = 4,
                            Descripcion = "Cambio pastillas de freno",
                            FechaCreacion = new DateTime(2025, 11, 19, 14, 29, 12, 110, DateTimeKind.Local).AddTicks(5566),
                            Nombre = "Cambio de Pastillas",
                            PrecioBase = 60.00m,
                            RequiereAutorizacion = false,
                            TiempoEstimadoMinutos = 90
                        });
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.Vehiculo", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehiculoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Kilometraje")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroChasis")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("NumeroMotor")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TipoCombustible")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Transmision")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VehiculoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.Factura", b =>
                {
                    b.HasOne("MotorTechService.Models.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotorTechService.Models.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotorTechService.Models.Entities.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("Facturas")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");

                    b.Navigation("OrdenTrabajo");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.HistorialMantenimiento", b =>
                {
                    b.HasOne("MotorTechService.Models.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotorTechService.Models.Entities.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany()
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MotorTechService.Models.Entities.Vehiculo", "Vehiculo")
                        .WithMany("HistorialMantenimientos")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("OrdenTrabajo");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.HistorialOrden", b =>
                {
                    b.HasOne("MotorTechService.Models.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotorTechService.Models.Entities.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("OrdenTrabajo");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.MovimientoInventario", b =>
                {
                    b.HasOne("MotorTechService.Models.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MotorTechService.Models.Entities.Repuesto", "Repuesto")
                        .WithMany("MovimientosInventario")
                        .HasForeignKey("RepuestoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Repuesto");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.OrdenTrabajo", b =>
                {
                    b.HasOne("MotorTechService.Models.Entities.Cliente", "Cliente")
                        .WithMany("OrdenesTrabajo")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotorTechService.Models.Entities.Empleado", "EmpleadoAsignado")
                        .WithMany("OrdenesAsignadas")
                        .HasForeignKey("EmpleadoAsignadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MotorTechService.Models.Entities.Empleado", "EmpleadoRecepcion")
                        .WithMany("OrdenesRecibidas")
                        .HasForeignKey("EmpleadoRecepcionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MotorTechService.Models.Entities.Vehiculo", "Vehiculo")
                        .WithMany("OrdenesTrabajo")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("EmpleadoAsignado");

                    b.Navigation("EmpleadoRecepcion");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.OrdenTrabajoRepuesto", b =>
                {
                    b.HasOne("MotorTechService.Models.Entities.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("Repuestos")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotorTechService.Models.Entities.Repuesto", "Repuesto")
                        .WithMany("OrdenTrabajoRepuestos")
                        .HasForeignKey("RepuestoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenTrabajo");

                    b.Navigation("Repuesto");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.OrdenTrabajoServicio", b =>
                {
                    b.HasOne("MotorTechService.Models.Entities.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("Servicios")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotorTechService.Models.Entities.Servicio", "Servicio")
                        .WithMany("OrdenTrabajoServicios")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenTrabajo");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.Pago", b =>
                {
                    b.HasOne("MotorTechService.Models.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotorTechService.Models.Entities.Factura", "Factura")
                        .WithMany("Pagos")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.RegistroTiempo", b =>
                {
                    b.HasOne("MotorTechService.Models.Entities.Empleado", "Empleado")
                        .WithMany("RegistrosTiempo")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotorTechService.Models.Entities.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany()
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Empleado");

                    b.Navigation("OrdenTrabajo");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.Repuesto", b =>
                {
                    b.HasOne("MotorTechService.Models.Entities.CategoriaRepuesto", "CategoriaRepuesto")
                        .WithMany("Repuestos")
                        .HasForeignKey("CategoriaRepuestoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaRepuesto");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.Servicio", b =>
                {
                    b.HasOne("MotorTechService.Models.Entities.CategoriaServicio", "CategoriaServicio")
                        .WithMany("Servicios")
                        .HasForeignKey("CategoriaServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaServicio");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.Vehiculo", b =>
                {
                    b.HasOne("MotorTechService.Models.Entities.Cliente", "Cliente")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.CategoriaRepuesto", b =>
                {
                    b.Navigation("Repuestos");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.CategoriaServicio", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.Cliente", b =>
                {
                    b.Navigation("OrdenesTrabajo");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.Empleado", b =>
                {
                    b.Navigation("OrdenesAsignadas");

                    b.Navigation("OrdenesRecibidas");

                    b.Navigation("RegistrosTiempo");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.Factura", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.OrdenTrabajo", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("HistorialEstados");

                    b.Navigation("Repuestos");

                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.Repuesto", b =>
                {
                    b.Navigation("MovimientosInventario");

                    b.Navigation("OrdenTrabajoRepuestos");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.Servicio", b =>
                {
                    b.Navigation("OrdenTrabajoServicios");
                });

            modelBuilder.Entity("MotorTechService.Models.Entities.Vehiculo", b =>
                {
                    b.Navigation("HistorialMantenimientos");

                    b.Navigation("OrdenesTrabajo");
                });
#pragma warning restore 612, 618
        }
    }
}
